### ISSUE TITLE
Broken Functionality: A custom tray menu for the application broke in macOS 10.14.3

### ISSUE THREAD

**Issue by JustinGuerra** [encryptstore/EncryptStore#30]
**Describe the bug**
The application and the message "Hello, world." load fine, but the following error message appears after the application is launched in Mac OS 10.14.3: 
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /Users/justinguerra/Repos/EncryptStore/app/public/assets/tray.png
    at addInTray (/Users/justinguerra/Repos/EncryptStore/app/public/Electron.js:44:10)
    at App.app.on (/Users/justinguerra/Repos/EncryptStore/app/public/Electron.js:70:3)
    at App.emit (events.js:187:15)

**To Reproduce**
1. type "yarn start" in the command line

**Expected behavior**
loading into Tray

**Screenshots**
![image](https://user-images.githubusercontent.com/11654334/54243148-49f54d80-44f5-11e9-9e6a-411ff2faaf28.png)
![image](https://user-images.githubusercontent.com/11654334/54243315-eae40880-44f5-11e9-8862-6f9370b610c0.png)

**Desktop:**
 - OS: Mac OS 10.14.3

**Additional context**

**Comment by DanielHix** [comment]
Hey Justin would you mind trying to fix this? I don't have a Mac and would have to find and install a Mac VM to tackle it.

**Comment by JustinGuerra** [comment]
I've isolated this to the addInTray const. There are methods of the Tray class that can not be used on macOS and I will have to continue troubleshooting this issue tomorrow.

**Comment by DanielHix** [comment]
Look into moving the entire tray feature out of the electron.js file @JustinGuerra and instead put it in it's own file and have it export it. We can then in turn call on it in electron.js but it will be separated, and give us a possibility of moving it to a setting later. 

As for MacOS only things, check into how I did the paths for the icons and use that same method.
